title: "Bukola Adekunle"
description: 
theme: jekyll-theme-minimal
url: "https://Bukolagiant.github.io"

author:
 - name: "Bukola Adekunle"
 - email: "adekunlegiant@gmail.com"
 - linkedin: "https://www.linkedin.com/in/bukolaadekunle"
 - github: "https://github.com/bukolagiant"

navigation:
 - name: "Home"
 - link: "/"
 - name: "Projects"
 - link: "
 



